#sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)

  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  #SERVICE
  - export SERVICE=michaelilyin/jee-mobile-service
  - docker build -t $SERVICE:$COMMIT ./service
  - docker tag $SERVICE:$COMMIT $SERVICE:$TAG
  - docker push $SERVICE:$TAG
